on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ['3.11', '3.12', '3.13']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add this step before installing Python dependencies
      - name: Install Cairo dependencies
        run: sudo apt-get update && sudo apt-get install -y libcairo2-dev pkg-config

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt